# Generated by Django 4.2.14 on 2025-09-25 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='UserOperacionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='users.modulo')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='users.operacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_overrides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='useroperacionoverride',
            constraint=models.UniqueConstraint(fields=('user', 'modulo', 'operacion'), name='unique_user_override'),
        ),
    ]
