# Generated by Django 4.2.14 on 2025-10-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_operacion_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=128)),
                ('dni', models.CharField(max_length=16)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=32)),
                ('ubicacion_parcela', models.TextField()),
                ('descripcion_terreno', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=32)),
            ],
        ),
    ]
