# Generated by Django 5.0.14 on 2025-10-30 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parcels_cultivo',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_estimada_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'parcels_etapa',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ReglaPorEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100)),
                ('minimo', models.FloatField(blank=True, null=True)),
                ('maximo', models.FloatField(blank=True, null=True)),
                ('accion_si_menor', models.TextField(blank=True, null=True)),
                ('accion_si_mayor', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='crops.etapa')),
            ],
            options={
                'db_table': 'parcels_reglaporetapa',
                'ordering': ['-prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='crops.cultivo')),
            ],
            options={
                'db_table': 'parcels_variedad',
                'unique_together': {('cultivo', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='crops.variedad'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('variedad', 'nombre')},
        ),
    ]
