# Generated by Django 4.2.14 on 2025-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='horarios_por_defecto',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='limite_lecturas_dia',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='veces_por_dia',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='frecuencia_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
