# Generated by Django 5.0.14 on 2025-11-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='frecuencia_minutos',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='limite_lecturas_dia',
        ),
        migrations.AlterField(
            model_name='plan',
            name='horarios_por_defecto',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
