# Generated by Django 4.2.11 on 2025-12-10 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login', 'Login'), ('consulta', 'Consulta'), ('actividad', 'Actividad'), ('alerta', 'Alerta'), ('cambio', 'Cambio')], max_length=32)),
                ('module', models.CharField(blank=True, max_length=64, null=True)),
                ('action', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'created_at'], name='brain_audit_event_767e96_idx'), models.Index(fields=['user', 'created_at'], name='brain_audit_user_id_e50abe_idx')],
            },
        ),
    ]
