# Generated by Django 4.2.14 on 2025-10-22 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcels', '0003_cultivo_remove_parcela_tipo_cultivo_variedad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_estimada_dias', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='cultivo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='etapa_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variedad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReglaPorEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100)),
                ('minimo', models.FloatField(blank=True, null=True)),
                ('maximo', models.FloatField(blank=True, null=True)),
                ('accion_si_menor', models.TextField(blank=True, null=True)),
                ('accion_si_mayor', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='parcels.etapa')),
            ],
            options={
                'ordering': ['-prioridad', 'id'],
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='parcels.variedad'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='etapa_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_en_etapa', to='parcels.etapa'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('variedad', 'nombre')},
        ),
    ]
