# Generated by Django 4.2.14 on 2025-10-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_etapa_cultivo_descripcion_parcela_etapa_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
