# Generated by Django 6.0 on 2025-12-07 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre del usuario que envió el mensaje', max_length=150)),
                ('message', models.TextField(help_text='Contenido del mensaje')),
                ('is_user', models.BooleanField(default=True, help_text='True si es mensaje del usuario, False si es del bot')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_air', models.FloatField(help_text='Temperatura del aire en °C')),
                ('humidity_air', models.FloatField(help_text='Humedad del aire en %')),
                ('humidity_soil', models.FloatField(help_text='Humedad del suelo en %')),
                ('conductivity_ec', models.FloatField(help_text='Conductividad eléctrica en dS/m')),
                ('temperature_soil', models.FloatField(help_text='Temperatura del suelo en °C')),
                ('solar_radiation', models.FloatField(help_text='Radiación solar en W/m²')),
                ('pest_risk', models.CharField(choices=[('Bajo', 'Bajo'), ('Moderado', 'Moderado'), ('Alto', 'Alto')], default='Bajo', help_text='Nivel de riesgo de plagas', max_length=20)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, help_text='Última actualización de datos')),
            ],
            options={
                'verbose_name': 'Datos de Cultivo',
                'verbose_name_plural': 'Datos de Cultivo',
            },
        ),
    ]
