# Generated by Django 4.2.14 on 2025-09-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], max_length=20)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('parcela_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodo_id', models.CharField(max_length=50)),
                ('parcela_id', models.IntegerField()),
                ('sensor_tipo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
