# Generated by Django 4.2.14 on 2025-10-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='recomendacion',
        ),
        migrations.AddField(
            model_name='task',
            name='decision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('ia', 'IA')], default='manual', max_length=10),
        ),
    ]
