# Generated by Django 4.2.14 on 2025-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='origen',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('ia', 'IA')], max_length=20, null=True),
        ),
    ]
