# Generated by Django 5.0.14 on 2025-10-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=10)),
                ('bateria', models.IntegerField(blank=True, null=True)),
                ('senal', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos_maestros', to='parcels.parcela')),
            ],
        ),
        migrations.CreateModel(
            name='NodoSecundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=10)),
                ('bateria', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secundarios', to='nodes.node')),
            ],
        ),
        migrations.CreateModel(
            name='TokenNodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('valido', 'Válido'), ('en_gracia', 'En gracia'), ('invalidado', 'Invalidado')], default='valido', max_length=15)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='nodes.node')),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='nodes_token_key_375b05_idx')],
            },
        ),
    ]
