# Generated by Django 4.2.14 on 2025-10-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='nodosecundario',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='nodosecundario',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='nodosecundario',
            name='senal',
        ),
    ]
