# Generated by Django 4.2.14 on 2025-10-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_remove_node_usuario_remove_nodosecundario_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=10),
        ),
        migrations.AlterField(
            model_name='nodosecundario',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nodosecundario',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivo', to='nodes.node'),
        ),
    ]
