# Generated by Django 4.2.14 on 2025-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_alter_node_codigo_alter_node_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodosecundario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=10),
        ),
    ]
