# Generated by Django 4.2.14 on 2025-10-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_alter_nodosecundario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodosecundario',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secundarios', to='nodes.node'),
        ),
    ]
