"""
Django settings for agro_ai_platform project.

Generated by Django 4.0.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import cloudinary

BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables del archivo .env
load_dotenv(BASE_DIR / '.env')

def _csv(key, default=""):
    raw = os.getenv(key, default) or ""
    return [x.strip() for x in raw.split(",") if x.strip()]

SECRET_KEY = os.getenv('SECRET_KEY', 'your-secret-key')
DEBUG = os.getenv("DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = _csv("ALLOWED_HOSTS", "localhost,127.0.0.1")

# Acepta tanto dominios completos como URLs con esquema
_csrf = _csv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    v if "://" in v else f"https://{v}"
    for v in _csrf
] if _csrf else []

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'authentication',
    'users',
    'parcels',
    'plans',
    "ai",
    'nodes',
    'recommendations',
    'crops',
    # 'tokensapp',
    'tasks',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'brain',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agro_ai_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agro_ai_platform.wsgi.application'

DB_URL = os.getenv('DATABASE_URL')
if DB_URL:
    # Render requiere SSL; si tu URL no tiene ?sslmode=require, manten ssl_require=True
    DATABASES = {
        'default': dj_database_url.parse(DB_URL, conn_max_age=600, ssl_require=True)
    }
else:
    # Fallback local (opcional)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'agro_ai_db'),
            'USER': os.getenv('POSTGRES_USER', 'agro_ai_user'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'password'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
# Zona horaria (Perú) y TZ activada
TIME_ZONE = 'America/Lima'
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'authentication.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Agro AI Platform API',
    'DESCRIPTION': 'API para autenticación, parcelas y planes.',
    'VERSION': '0.1',
    'SECURITY_SCHEMES': {'TokenAuth': {'type': 'apiKey','in':'header','name':'Authorization'}},
    'SECURITY': [{'TokenAuth': []}],
}

# MongoDB (solo estas dos variables desde .env)
MONGO_URL = os.getenv("MONGO_URL", "")
MONGO_DB = os.getenv("MONGO_DB", "sensors_db")

# Eliminar variables/alias duplicados (MONGO_URI, MONGODB_URI, etc.). Centralizar uso en agro_ai_platform.mongo.get_db()

# CORS
def _parse_origins(value: str):
    return [o.strip().rstrip('/') for o in value.split(',') if o.strip()]

CORS_ALLOWED_ORIGINS = _parse_origins(
    os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000'
    )
)

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

if not DEBUG:
    SECURE_HSTS_SECONDS = 60
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
# Solo en desarrollo: relajar CORS / ALLOWED_HOSTS para facilitar pruebas con túneles
if DEBUG:
    # Permite cualquier origen (útil para frontend local / túneles). NO usar en producción.
    CORS_ALLOW_ALL_ORIGINS = True
    # Permitir envío de cookies/credenciales si lo necesitas en dev:
    CORS_ALLOW_CREDENTIALS = True

    # Evita DisallowedHost en túneles/hosts dinámicos (usar solo en dev)
    # Alternativa más segura: listar explícitamente los hosts/túneles en ALLOWED_HOSTS
    ALLOWED_HOSTS = ["*"]

CLOUDINARY_URL = os.getenv("CLOUDINARY_URL")
if CLOUDINARY_URL:
    cloudinary.config(cloudinary_url=CLOUDINARY_URL)