# Generated by Django 5.0.14 on 2025-10-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('detalle', models.TextField()),
                ('score', models.FloatField(default=0)),
                ('source', models.CharField(default='rule', max_length=50)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('riego', 'Riego'), ('fertilizacion', 'Fertilización'), ('plaga', 'Control de plagas'), ('cosecha', 'Cosecha'), ('alerta', 'Alerta')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='parcels.parcela')),
            ],
        ),
    ]
