# Generated by Django 4.2.14 on 2025-09-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('detalle', models.TextField()),
                ('score', models.FloatField(default=0)),
                ('source', models.CharField(default='rule', max_length=50)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('riego', 'Riego'), ('fertilizacion', 'Fertilización'), ('plaga', 'Control de plagas'), ('cosecha', 'Cosecha')], default='general', max_length=50)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('descartado', 'Descartado')], default='nuevo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='parcels.parcela')),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to='recommendations.recommendation')),
            ],
        ),
    ]
