# Generated by Django 4.2.11 on 2025-11-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='entity_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='entity_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('new', 'Nueva'), ('read', 'Leída'), ('archived', 'Archivada')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('riego', 'Riego'), ('fertilizacion', 'Fertilización'), ('plaga', 'Control de plagas'), ('cosecha', 'Cosecha'), ('alerta', 'Alerta')], default='alerta', max_length=50),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['parcela', 'created_at'], name='recommendat_parcela_46a5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['code'], name='recommendat_code_17932a_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['status'], name='recommendat_status_d2897f_idx'),
        ),
    ]
