# Generated by Django 4.2.14 on 2025-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='fecha_implementacion',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('riego', 'Riego'), ('fertilizacion', 'Fertilización'), ('plaga', 'Control de plagas'), ('cosecha', 'Cosecha'), ('alerta', 'Alerta')], default='general', max_length=50),
        ),
        migrations.DeleteModel(
            name='TaskItem',
        ),
    ]
