# Generated by Django 4.2.11 on 2025-11-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_options_recommendation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
