# Generated by Django 4.2.11 on 2025-11-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_recommendation_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='fingerprint',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
