# Generated by Django 4.2.11 on 2025-11-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_recommendation_fingerprint'),
    ]

    operations = [
    ]
