# Generated by Django 4.2.11 on 2025-11-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_make_fingerprint_not_null'),
        ('recommendations', '0005_make_fingerprint_not_null'),
    ]

    operations = [
    ]
